# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f377b37573e8a2bcb3a43167b9196c56e394b51d6f92f841c8b640bc03270c6b352ea8c0f94882bb9b446fdb06ab9da0f72904450c5ae4348aa276ee1833ead

test:
  secret_key_base: 8416b2277d365c44416def01865ff620bde7a23f339df52b3787b5aa284462db234fc6e277abf590b1c2cfdbec2ef4e024f184aabb35e586909898b2dcba597f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
